#!/usr/bin/env python3
"""Rasterize the checked-in Fluent SVG paths into C alpha masks."""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ICONS = ("cursor", "rectangle", "target", "target-clear")
TOKEN = re.compile(r"[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?")


def parse_path(data: str) -> list[list[tuple[float, float]]]:
    tokens = TOKEN.findall(data)
    contours: list[list[tuple[float, float]]] = []
    contour: list[tuple[float, float]] = []
    current = (0.0, 0.0)
    start = current
    command = ""
    index = 0

    def number() -> float:
        nonlocal index
        value = float(tokens[index])
        index += 1
        return value

    def finish() -> None:
        nonlocal contour
        if contour:
            if contour[-1] != contour[0]:
                contour.append(contour[0])
            contours.append(contour)
            contour = []

    while index < len(tokens):
        if tokens[index].isalpha():
            command = tokens[index]
            index += 1
        if command == "M":
            finish()
            current = (number(), number())
            start = current
            contour = [current]
            command = "L"
        elif command == "L":
            current = (number(), number())
            contour.append(current)
        elif command == "H":
            current = (number(), current[1])
            contour.append(current)
        elif command == "V":
            current = (current[0], number())
            contour.append(current)
        elif command == "C":
            control1 = (number(), number())
            control2 = (number(), number())
            end = (number(), number())
            origin = current
            for step in range(1, 25):
                t = step / 24.0
                u = 1.0 - t
                point = (
                    u**3 * origin[0]
                    + 3 * u**2 * t * control1[0]
                    + 3 * u * t**2 * control2[0]
                    + t**3 * end[0],
                    u**3 * origin[1]
                    + 3 * u**2 * t * control1[1]
                    + 3 * u * t**2 * control2[1]
                    + t**3 * end[1],
                )
                contour.append(point)
            current = end
        elif command in ("Z", "z"):
            if contour and contour[-1] != start:
                contour.append(start)
            current = start
            finish()
            command = ""
        else:
            raise ValueError(f"Unsupported SVG path command: {command!r}")
    finish()
    return contours


def winding_number(contours: list[list[tuple[float, float]]],
                   x: float, y: float) -> int:
    winding = 0
    for contour in contours:
        for first, second in zip(contour, contour[1:]):
            if first[1] <= y:
                if second[1] > y and (
                    (second[0] - first[0]) * (y - first[1])
                    - (x - first[0]) * (second[1] - first[1])
                ) > 0:
                    winding += 1
            elif second[1] <= y and (
                (second[0] - first[0]) * (y - first[1])
                - (x - first[0]) * (second[1] - first[1])
            ) < 0:
                winding -= 1
    return winding


def rasterize(svg_path: Path) -> dict[int, bytes]:
    root = ET.parse(svg_path).getroot()
    path = next(element for element in root if element.tag.endswith("path"))
    contours = parse_path(path.attrib["d"])
    supersample = 8
    canvas_size = 40 * supersample
    image = Image.new("L", (canvas_size, canvas_size), 0)
    pixels = image.load()
    for py in range(canvas_size):
        y = (py + 0.5) * 20.0 / canvas_size
        for px in range(canvas_size):
            x = (px + 0.5) * 20.0 / canvas_size
            if winding_number(contours, x, y):
                pixels[px, py] = 255
    return {
        size: image.resize((size, size), Image.Resampling.LANCZOS).tobytes()
        for size in (20, 40)
    }


def format_mask(name: str, size: int, values: bytes) -> str:
    lines = []
    for offset in range(0, len(values), 20):
        row = ", ".join(f"{value:3d}" for value in values[offset : offset + 20])
        lines.append(f"        {row},")
    return f"    {{ /* {name} */\n" + "\n".join(lines) + "\n    }"


def main() -> None:
    masks = {
        name: rasterize(ROOT / "assets" / "icons" / f"{name}.svg")
        for name in ICONS
    }
    output = [
        "/* Generated by tools/generate_tool_icon_masks.py from the MIT-licensed",
        "   Microsoft Fluent System Icons in assets/icons. Do not edit by hand. */",
        "#ifndef GOLDENS_UI_TOOL_ICON_MASKS_H",
        "#define GOLDENS_UI_TOOL_ICON_MASKS_H",
        "",
    ]
    for size in (20, 40):
        output.append(
            f"static const unsigned char golden_tool_icon_masks_{size}"
            f"[{len(ICONS)}][{size * size}] = {{"
        )
        output.append(",\n".join(
            format_mask(name, size, masks[name][size]) for name in ICONS
        ))
        output.extend(("};", ""))
    output.extend(("#endif", ""))
    (ROOT / "src" / "ui_tool_icon_masks.h").write_text(
        "\n".join(output), encoding="ascii"
    )


if __name__ == "__main__":
    main()
